# on merge to main
# run `typedoc ./src/index.ts --out ./typedoc-temp`
# checkout website repo
# create branch update-generated-reference
# copy ./typedoc-temp to website:./api
# commit "Update TypeDoc generated API reference"
# push?
# create PR "Update TypeDoc generated API reference"

name: Update API Reference

on:
  push:
    # branches:
    #   - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate TypeDoc Reference
        run: |
          npm install
          npx typedoc ./src/index.ts --out ./typedoc-temp

      - name: List output of typedoc
        run: ls -la typedoc-temp

      - name: Checkout Website Repository
        uses: actions/checkout@v4
        with:
          repository: "bzr-sys/bazaar-website"
          token: ${{ secrets.ACCESS_TOKEN }}
          path: "website"

      - name: Create New Branch
        run: |
          cd website
          git checkout -b update-generated-reference

      - name: Show current directory and list contents
        run: |
          pwd
          ls -la

      - name: Copy Reference to Website
        run: |
          cp -R typedoc-temp/. website/api/

      - name: Commit Changes
        run: |
          cd website
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./api
          git commit -m "Update TypeDoc generated API reference"

      - name: Push Changes
        run: |
          cd website
          git push origin update-generated-reference

      - name: Create Pull Request
        run: |
          cd website
          gh pr create --title "Update TypeDoc generated API reference" --body "This PR updates the API Reference for the project." --head update-generated-reference --base main
